<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Klavier.Core\Klavier.Core.csproj" />
    <ProjectReference Include="..\Klavier.Config\Klavier.Config.csproj" />
  </ItemGroup>
</Project>
